### ISSUE TITLE
Unwanted ellipsis in IE11 

### ISSUE THREAD

**Issue by limonte** [predixdesignsystem/px-dropdown#77]
Instead of `10` `20` `30` IE shows `1…` `2…` `3…`:

![image](https://user-images.githubusercontent.com/6059356/36717752-f8f1969a-1ba7-11e8-914c-63de5c707066.png)

Live demo: https://private-red.glitch.me/

Source code: https://glitch.com/edit/#!/private-red?path=index.html:25:72

**Comment by alump** [comment]
As a side note, i spent hours trying to find a workaround for this issue, but none of those worked. So proper fix is needed.

**Comment by benoitjchevalier** [comment]
Likely related to #73

**Comment by randyaskin** [comment]
I fought with this for an additional 3 hours this morning, I can't figure out why iron-dropdown assigns a different max-width in IE than it does in other browsers. I tried adjusting padding to a whole-rem value (IE rounds 0.6667rem to 0.66rem instead), changing box-sizing, manually overriding width and max-width in various places, etc and nothing worked.

As a workaround, I've added a property for `disable-truncate` in v4.7.0 of px-dropdown that turns off truncation - items longer than the maximum width will just wrap instead of truncating, and short items like this page size dropdown will appear as expected if `disable-truncate` is set.

Leaving this open in case an actual solution can be found.
